{
starbound: [
  'nick',
  'w',
  'r',
  'boxes',
  'debug',
  'fullbright',
  'pvp',
  'listcid',
  'serverreload',
  'reload',
  'setgravity',
  'spawngun',
  'spawnitem',
  'spawnliquid',
  'spawnmonster',
  'spawnnpc',
  'spawnshield',
  'spawnsword',
  'timewarp',
  'togglelayer',
  'togglemap',
  'globalalert',
  'serveralert',
  'alert'],
starnub: [
  'info',
  'help',
  'online',
  'players',
  'who',
  'my',
  'get',
  'goonline',
  'gooffline',
  'account',
  'admin',
  'kick',
  'ban',
  'tban',
  'mute',
  'shutdown',
  'stop',
  'off',
  'plugin']
}