name: CommandParser
class: org.starnub.essentials.CommandParser
version: 1.0
author: Underbalanced
url: http://www.starnub.org
dependencies: None
languages: english
configuration: yes
commands: yes
commands_name: commandparser
commands_alias: cp
runnables: false
runnable_classes: ['']
description: |-
    Under Current Development.
    Features:
    Additions:
    Removals:
