{
  "name": "CommandParser",
  "class": "commandparser.CommandParser",
    "details": {
    "languages": ['english'],
    "version": 1.0,
    "description": "None",
    "dependencies": ['ChatParser'],
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "CommandParser",
    "alias": "cp",
  },
  "runnables": {
    "has": false,
    "runnables": []
  },
  "additional_permissions": [ 'commandparser.chat',
                              'commandparser.chat.#',
                              'commandparser.command',
                              'commandparser.command.#'],
}