name: Essentials
class: essentials.Essentials
version: 1.0
author: Underbalanced
url: http://www.starnub.org
dependencies: None
languages: english
configuration: yes
commands: yes
commands_name: essentials
commands_alias: es
runnables: false
runnable_classes: ['essentials.Test1', 'essentials.Test2']
description: |-
    Under Current Development.
    Features:
    Additions:
    Removals:
