{
  "name": "Essentials",
  "class": "essentials.Essentials",
    "details": {
    "languages": "english",
    "version": 1.0,
    "description": "None",
    "dependencies": "None",
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "essentials",
    "alias": "es",
  },
  "runnables": {
    "has": false, 
    "runnables": []
  }, 
  "additional_permissions": [],
  "yaml_files": [{filename.yml: directory}, {filename.yml: directory}],
}