{
    colors:{
        "server":{
            name: "white",
            chat: "white"
        },
        "global":{
            name: #FFFF00,
            chat: #FFFF00
        }
    },
    global_rate_limit:{
        messages: 3000,
        commands: 1000
    },
    block:{
        repeat:{
            messages: true,
            characters: true
        }
        caps:{
            caps: true,
            percentage: 50.0,
        }
    },
    word_filter:{
        enabled: true,
    },
    reply_messages:{
        spam: "Woah! Slow down your spamming the server."
    }
}