{
  "name": "ChatManager",
  "class": "ChatManager",
    "details": {
    "languages": ['english'],
    "version": 1.0,
    "description": "None",
    "dependencies": [],
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "chatman",
    "alias": "cm",

  },
  "runnables": {
    "has": false,
    "runnables": []
  },
  "additional_permissions": [''],
}

